basePath: '{{.BasePath}}'
host: 127.0.0.1:8000
info:
  contact: {}
  description: An example of gin
  license:
    name: caicai
    url: https://erry.io
  termsOfService: https://erry.io
  title: Golang Gin API
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: state
        in: query
        name: state
        type: integer
      - description: createdBy
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"data":{},"msg":"error"}'
          schema:
            type: string
      summary: Get multiple article tags
swagger: "2.0"
